name: Test proxy
on: [push, pull_request]

jobs:
  test_proxy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install python dependencies
      run: pip install -r requirements.txt && pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: ruff check proxy/